(function (NS) {
  'use strict';

  // Closed O-mesh around an airfoil — MATLAB Omesh.m + Hyp_gen4.
  //
  // Inner boundary (j=0): closed profile loop (upper TE → LE → lower → upper TE).
  // Outward layers generated by hyperbolic marching (HypGen4).
  // Periodic in circumferential direction (true O-topology).

  NS.CMesh = {};

  function rotate(x, y, cx, cy, sin_a, cos_a) {
    const dx = x - cx, dy = y - cy;
    return { x: cx + dx * cos_a - dy * sin_a, y: cy + dx * sin_a + dy * cos_a };
  }

  // Same ordering as MATLAB NACA2 + Omesh (I = n:-1:2).
  function buildProfileLoop(nacaPts, rot) {
    const lower = nacaPts.lower; // TE → LE
    const upper = nacaPts.upper; // LE → TE
    const raw = [];
    for (let k = 0; k < lower.length; k++) {
      raw.push(rot(lower[k].x, lower[k].y));
    }
    for (let k = 1; k < upper.length; k++) {
      raw.push(rot(upper[k].x, upper[k].y));
    }
    const loop = [];
    for (let k = raw.length - 1; k >= 1; k--) {
      loop.push(raw[k]);
    }
    return loop;
  }

  function signedAreaLoop(loop) {
    let area = 0;
    const n = loop.length;
    for (let k = 0; k < n; k++) {
      const p = loop[k];
      const q = loop[(k + 1) % n];
      area += p.x * q.y - q.x * p.y;
    }
    return 0.5 * area;
  }

  function resampleLoopClustered(loop, n1, teCluster, leCluster) {
    const n = loop.length;
    let lePos = 0;
    let minX = Infinity;
    for (let k = 0; k < n; k++) {
      if (loop[k].x < minX) { minX = loop[k].x; lePos = k; }
    }

    const cum = [0];
    for (let i = 1; i < n; i++) {
      const dx = loop[i].x - loop[i - 1].x;
      const dy = loop[i].y - loop[i - 1].y;
      cum.push(cum[i - 1] + Math.hypot(dx, dy));
    }
    const total = cum[cum.length - 1];
    const leFrac = cum[lePos] / Math.max(total, 1e-14);

    const M = 4096;
    const W = new Float64Array(M);
    for (let k = 1; k < M; k++) {
      const s = k / (M - 1);
      const dTE = Math.min(s, 1 - s);
      const dLE = Math.min(Math.abs(s - leFrac), 1 - Math.abs(s - leFrac));
      const w = 1
        + teCluster * Math.exp(-Math.pow(dTE / 0.035, 2))
        + leCluster * Math.exp(-Math.pow(dLE / 0.055, 2));
      W[k] = W[k - 1] + w / (M - 1);
    }
    const wTotal = W[M - 1];

    const out = [];
    let leIndex = 0;
    let minXOut = Infinity;
    for (let k = 0; k < n1; k++) {
      const target = (k / n1) * wTotal;
      let lo = 0, hi = M - 1;
      while (lo < hi) {
        const mid = (lo + hi) >> 1;
        if (W[mid] < target) lo = mid + 1; else hi = mid;
      }
      const s = lo / (M - 1);
      const arcTarget = s * total;

      let i = 1;
      while (i < cum.length - 1 && cum[i] < arcTarget) i++;
      const seg = cum[i] - cum[i - 1];
      const f = seg < 1e-14 ? 0 : (arcTarget - cum[i - 1]) / seg;
      out.push({
        x: loop[i - 1].x + f * (loop[i].x - loop[i - 1].x),
        y: loop[i - 1].y + f * (loop[i].y - loop[i - 1].y),
      });
      if (out[k].x < minXOut) { minXOut = out[k].x; leIndex = k; }
    }
    return { pts: out, leIndex, teIndex: 0 };
  }

  NS.CMesh.build = function (nacaPts, params) {
    const { ni, nj, alpha, hypK, hypLambda, hypDnScale, teCluster, leCluster } = params;

    const alpha_rad = alpha * Math.PI / 180;
    const sin_a = Math.sin(alpha_rad), cos_a = Math.cos(alpha_rad);
    const rot = (x, y) => rotate(x, y, 0.25, 0.0, sin_a, cos_a);

    const n1 = ni;
    const n2 = nj + 1;
    const profileLoop = buildProfileLoop(nacaPts, rot);
    let { pts: profile, leIndex, teIndex } = resampleLoopClustered(
      profileLoop, n1, teCluster ?? 4, leCluster ?? 3);
    // Hyp_gen4 normal is outward for CW loops; reverse if CCW.
    if (signedAreaLoop(profile) > 0) {
      profile.reverse();
      leIndex = (n1 - leIndex) % n1;
    }

    const X = Array.from({ length: n1 }, () => new Float64Array(n2));
    const Y = Array.from({ length: n1 }, () => new Float64Array(n2));
    for (let i = 0; i < n1; i++) {
      X[i][0] = profile[i].x;
      Y[i][0] = profile[i].y;
    }

    NS.HypGen4.generate(X, Y, { K: hypK, lambda: hypLambda, dnScale: hypDnScale });

    const nodeX = new Float64Array((ni + 1) * (nj + 1));
    const nodeY = new Float64Array((ni + 1) * (nj + 1));
    const nodeIdx = (I, J) => J * (ni + 1) + I;

    for (let j = 0; j <= nj; j++) {
      for (let i = 0; i < ni; i++) {
        const k = nodeIdx(i, j);
        nodeX[k] = X[i][j];
        nodeY[k] = Y[i][j];
      }
      nodeX[nodeIdx(ni, j)] = X[0][j];
      nodeY[nodeIdx(ni, j)] = Y[0][j];
    }

    const isWallCell = new Uint8Array(ni);
    isWallCell.fill(1);

    return {
      ni, nj,
      nodeX, nodeY, nodeIdx,
      isWallCell,
      surfaceStart: 0,
      surfaceEnd: ni - 1,
      leIndex,
      teIndex,
      seamIndex: 0,
    };
  };
})(window.AFL);
