(function (NS) {
  'use strict';

  // Build grid metrics (face normals, areas, cell volumes/centers) from pre-computed node
  // coordinates generated by CMesh.build().
  //
  // Indexing (same as finiteVolumeMethod reference):
  //   Nodes:   nodeIdx(I,J) = J*(ni+1)+I,   I in [0,ni],   J in [0,nj]
  //   Cells:   cellIdx(i,j) = j*ni+i,        i in [0,ni-1], j in [0,nj-1]
  //   I-faces: ifaceIdx(I,j)= j*(ni+1)+I,   I in [0,ni],   j in [0,nj-1]
  //   J-faces: jfaceIdx(i,J)= J*ni+i,        i in [0,ni-1], J in [0,nj]
  //   Extended:extIdx(i,j)  = j*(ni+2)+i,    ghost layers included

  NS.Grid = {};

  NS.Grid.build = function (cmesh) {
    const { ni, nj, nodeX, nodeY, nodeIdx, isWallCell, surfaceStart, surfaceEnd,
            leIndex, teIndex, seamIndex } = cmesh;

    // ── I-faces: (ni+1)*nj ───────────────────────────────────────────────────
    const niFaces = (ni + 1) * nj;
    const iFaceNx   = new Float64Array(niFaces);
    const iFaceNy   = new Float64Array(niFaces);
    const iFaceArea = new Float64Array(niFaces);
    const ifaceIdx  = (I, j) => j * (ni + 1) + I;

    for (let j = 0; j < nj; j++) {
      for (let I = 0; I <= ni; I++) {
        const n0 = nodeIdx(I, j);
        const n1 = nodeIdx(I, j + 1);
        const dX = nodeX[n1] - nodeX[n0];
        const dY = nodeY[n1] - nodeY[n0];
        const len = Math.sqrt(dX * dX + dY * dY);
        const k = ifaceIdx(I, j);
        iFaceNx[k]   =  dY / len;   // right-pointing normal (from cell i-1 to cell i)
        iFaceNy[k]   = -dX / len;
        iFaceArea[k] = len;
      }
    }

    // ── J-faces: ni*(nj+1) ───────────────────────────────────────────────────
    const njFaces = ni * (nj + 1);
    const jFaceNx   = new Float64Array(njFaces);
    const jFaceNy   = new Float64Array(njFaces);
    const jFaceArea = new Float64Array(njFaces);
    const jfaceIdx  = (i, J) => J * ni + i;

    for (let J = 0; J <= nj; J++) {
      for (let i = 0; i < ni; i++) {
        const n0 = nodeIdx(i,     J);
        const n1 = nodeIdx(i + 1, J);
        const dX = nodeX[n1] - nodeX[n0];
        const dY = nodeY[n1] - nodeY[n0];
        const len = Math.sqrt(dX * dX + dY * dY);
        const k = jfaceIdx(i, J);
        jFaceNx[k]   = -dY / len;   // upward-pointing normal (from cell j-1 to cell j)
        jFaceNy[k]   =  dX / len;
        jFaceArea[k] = len;
      }
    }

    // ── Cell volumes and centers: ni*nj ──────────────────────────────────────
    const ncells = ni * nj;
    const cellVol = new Float64Array(ncells);
    const cellCx  = new Float64Array(ncells);
    const cellCy  = new Float64Array(ncells);
    const cellIdx = (i, j) => j * ni + i;

    for (let j = 0; j < nj; j++) {
      for (let i = 0; i < ni; i++) {
        const n00 = nodeIdx(i,     j);
        const n10 = nodeIdx(i + 1, j);
        const n11 = nodeIdx(i + 1, j + 1);
        const n01 = nodeIdx(i,     j + 1);
        const x0 = nodeX[n00], y0 = nodeY[n00];
        const x1 = nodeX[n10], y1 = nodeY[n10];
        const x2 = nodeX[n11], y2 = nodeY[n11];
        const x3 = nodeX[n01], y3 = nodeY[n01];
        const vol = 0.5 * Math.abs((x0 - x2) * (y1 - y3) - (x1 - x3) * (y0 - y2));
        const k = cellIdx(i, j);
        cellVol[k] = Math.max(vol, 1e-20);
        cellCx[k]  = 0.25 * (x0 + x1 + x2 + x3);
        cellCy[k]  = 0.25 * (y0 + y1 + y2 + y3);
      }
    }

    return {
      ni, nj,
      nodeX, nodeY, nodeIdx,
      iFaceNx, iFaceNy, iFaceArea, ifaceIdx,
      jFaceNx, jFaceNy, jFaceArea, jfaceIdx,
      cellVol, cellCx, cellCy, cellIdx,
      extIdx: (i, j) => j * (ni + 2) + i,
      extStride: ni + 2,
      isWallCell, surfaceStart, surfaceEnd,
      leIndex: leIndex ?? Math.round(ni / 2),
      teIndex: teIndex ?? 0,
      seamIndex: seamIndex ?? 0,
    };
  };
})(window.AFL);
